/**
This program makes an LED to blink once a second (1000 milliseconds).
 * The on-board yellow LED will blink. If you connect a LED with a 220 ohm 
 * resistor to the RE0 pin it will also blink. The RE0 port (pin) is internally connected to the on-board LED. 
 * Written by Miguel Garcia-Ruiz
 * Ver. 1
 * July, 2020
*/

#include "mcc_generated_files/mcc.h" //necessary library generated by MCC that 
                                     //defines input/output pins (ports).

void main(void) //main program function
{
    // initializing the microcontroller board:
    SYSTEM_Initialize(); //it initializes microcontroller ports
    LED0_SetDigitalOutput(); //it sets up LED0 as output (it was already defined in mcc.h library)

    while (1) //infinite loop
    {
        LED0_SetLow(); //it turns off the on-board LED and RE0 pin
        __delay_ms(1000); //it pauses the program for 1 second (1000 milliseconds)
        LED0_SetHigh(); //it turns on on-board LED and RE0 pin
        __delay_ms(1000); //it pauses the program for 1 second (1000 milliseconds)
    }
}
/**
 End of File 
*/

